sync_calendar:
  fields:
    target_calendar:
      example: calendar.school
      selector:
        entity:
          domain: calendar
    student:
      example: Jane
      selector:
        text:
          multiple: true
    days:
      default: 14
      selector:
        number:
          min: 1
          max: 90
          unit_of_measurement: days
          mode: box
    prefix_student_name:
      default: true
      selector:
        boolean:
